### PR TITLE
Changes for improved layout, yellow/red card support, fix href logic

### PR DESCRIPTION
**Pull request by gingerbeardman**
- improved layout
- added yellow and red card events

- looks best with `SF Mono` font (get it inside Terminal.app)

screenshot

screen shot 2018-06-19 at 13 40 28

### CODE REVIEW

**Comment by dg01d** [comment]
Thanks for spotting the incorrect URL, can't believe I did that.

I tried your version of the layout, and it looks better. Merging, with thanks.

**Comment by gingerbeardman** [comment]
I will merge it upstream at bitbar-plugins if you PR

**Comment by gingerbeardman** [comment]
@dg01d the only thing I can't figure out is this bit of your original code.

what should it do?

```php
if (($todayData[$n]['status']) !== "in progress") {
    $time = $todayData[$n]['time'];
    $scores = $scores . " " . $time . " ⚽";
} else {
    $scores .= " href=$match";
}
```

ah! it's kick-off time, will fix if I can

**Comment by dg01d** [comment]
It adds the elapsed time to the currently running game, and adds a little football indicator.

**Comment by gingerbeardman** [comment]
I was in the process of moving these

elapsed time with football at end of updates
FT after full time

and just working on `@ 12:34` (user local time) underneath

how did my version look in Dark Mode on your system? It looked fine on my Mac i only colour the card symbols.

screen shot 2018-06-19 at 15 28 18

**Comment by gingerbeardman** [comment]
Here's what I'm happy with

screen shot 2018-06-19 at 15 42 31

**Comment by dg01d** [comment]
The default color text is unreadable in dark mode.

gingerbeard darkmode

**Comment by gingerbeardman** [comment]
Hmm, not for me. I guess it I must have lighter background?

screen shot 2018-06-19 at 17 41 05 screen shot 2018-06-19 at 17 41 13

**Comment by gingerbeardman** [comment]
Menu text should look the same as "Updated just now" so there's something amiss with your setup?

**Comment by dg01d** [comment]
Could it be a beta-issue? I'm not on the beta, I believe (reading the issues-page) that you are?

**Comment by gingerbeardman** [comment]
I'm using BitBar 1.9.2

(was on beta for a while)

**Comment by gingerbeardman** [comment]
I see the same with 2.0beta

screen shot 2018-06-19 at 18 21 16

**Comment by gingerbeardman** [comment]
My settings

screen shot 2018-06-19 at 18 22 32

**Pull request merged**
